---

- name: Update host
  become: true
  import_tasks: update.yml

- name: Install packages
  become: true
  import_tasks: install.yml
  
- name: Set hostname
  become: true
  hostname:
    name: "{{ inventory_hostname }}"
  when: inventory_hostname != 'local'
  