---

- name: "Update node"
  become: yes
  import_tasks: update.yml

- name: "Install packages"
  become: yes
  import_tasks: install.yml
  
- name: "Update hostname"
  become: yes
  import_tasks: hostname.yml

- name: "Update hosts"
  become: yes
  import_tasks: hosts.yml

- name: "Update resolv"
  become: yes
  import_tasks: resolv.yml
