---

- name: "Update existing packages"
  import_tasks: update-packages.yml

- name: "Install dependent packages"
  import_tasks: install-dependencies.yml
  
- name: "Install pip3"
  import_tasks: install-pip3
  when: 0

- name: "Configure git"
  import_tasks: configure-git.yml
  when: 0
  
- name: "Set hostname"
  import_tasks: set-hostname.yml

- name: "Update hosts"
  import_tasks: hosts.yml

- name: "Update resolv"
  import_tasks: resolv.yml
