---

portainer:
  image:
    name: 'portainer/portainer'
    tag: '1.22.0'
  service:
    name: portainer
    ports:
      http: 9000
    volumes:
      data: portainer_data
  storage: 
    configuration: "{{ storage_base }}/portainer"
