---

homeassistant:
  configuration:
    repo: 'github.com/greenthegarden/home-assistant-configuration.git'
  service:
    name: home-assistant
  image:
    name:
      linux: "homeassistant/home-assistant"
      rpi: "homeassistant/raspberrypi3-homeassistant"
    tag: latest
  storage: "{{ storage_base }}/home-assistant"
