---

emqx_deb: https://www.emqx.io/downloads/edge/v3.1-beta.1/emqx-edge-raspbian9-v3.1-beta.1_armhf.deb
emqx_zip: https://www.emqx.io/downloads/edge/v3.1-beta.1/emqx-edge-raspbian9-v3.1-beta.1.zip

emqx:
  service:
    name: emqx
    ports:
      mqtt: 1883
      http: 18083
    restart:
      policy: always
  image:
    name: emqx/emqx
    tag: v3.0.0

