---

# https://hub.docker.com/_/consul
# docker run -d --net=host -e 'CONSUL_LOCAL_CONFIG={"skip_leave_on_interrupt": true}' consul agent -server -bind=<external ip> -retry-join=<root agent ip> -bootstrap-expect=<number of server agents>
# docker run -d consul
- name: "Run image {{ consul.container.image }} as container {{ consul.container.name }}"
  docker_container:
    name: "{{ consul.container.name }}"
    image: "{{ consul.container.image }}"
    env:
      - CONSUL_LOCAL_CONFIG={"skip_leave_on_interrupt": true}
    published_ports:
      - "{{ consul.container.ports.http }}:9000"
    recreate: yes
    state: started


- name: run consul container with bootstrap
  docker_container:
    name: "{{ consul.container.name }}-{{ ansibe_hostname }}"
    image: "{{ consul_image }}"
    state: started
    detach: True
    restart_policy: always
    network_mode: bridge
    published_ports:
     - 8300:8300
     - 8301:8301
     - 8301:8301/udp
     - 8302:8302
     - 8302:8302/udp
     - 8400:8400
     - 8500:8500
     - "{{ docker_bridge_ip }}:8600:53"
     - "{{ docker_bridge_ip }}:8600:53/udp"   
    hostname: "{{ ansible_hostname }}"
    volumes:
    - /mnt:/data
    command: -server -advertise "{{consul_advertise}}" -bootstrap-expect "{{consul_bootstrap_expect}}" -ui-dir /ui
  when: consul_mode == "server" and consul_bootstrap == "1"

- name: run consul container with join ip
  docker_container:
    name: "{{ consul.container.name }}"
    image: "{{ consul_image }}"
    state: started
    detach: True
    restart_policy: always
    network_mode: bridge
    published_ports:
     - 8300:8300
     - 8301:8301
     - 8301:8301/udp
     - 8302:8302
     - 8302:8302/udp
     - 8400:8400
     - 8500:8500
     - "{{ docker_bridge_ip }}:8600:53"
     - "{{ docker_bridge_ip }}:8600:53/udp"
    volumes:
    - /mnt:/data
    hostname: "{{ ansible_hostname }}"
    command: -server -advertise "{{consul_advertise}}" -join "{{consul_join_ip}}" -ui-dir /ui
  when: consul_mode == "server" and consul_bootstrap == "0"

- name: run consul client container with join ip
  docker_container:
    name: "{{ consul.container.name }}"
    image: "{{ consul_image }}"
    state: started
    detach: True
    restart_policy: always
    network_mode: bridge
    published_ports:
     - 8300:8300
     - 8301:8301
     - 8301:8301/udp
     - 8302:8302
     - 8302:8302/udp
     - 8400:8400
     - 8500:8500
     - "{{ docker_bridge_ip }}:8600:53"
     - "{{ docker_bridge_ip }}:8600:53/udp"
    volumes:
    - /mnt:/data
    hostname: "{{ ansible_hostname }}"
    command: -advertise "{{consul_advertise}}" -join "{{consul_join_ip}}" -ui-dir /ui
  when: consul_mode == "agent" 
