---

# https://hub.docker.com/_/consul
# docker run -d consul
- name: "Run image {{ consul.container.image }} as container {{ consul.container.name }}"
  docker_container:
    name: "{{ consul.container.name }}"
    image: "{{ consul.container.image }}"
    published_ports:
      - "{{ consul.container.ports.http }}:9000"
    recreate: yes
    state: started
