---

# sudo apt-get update && sudo apt-get install libav-tools libssl-dev
- name: Update system and install libav-tools
  become: true
  package:
    name: "{{ item }}"
    state: latest
  loop:
    - libav-tools
    - libssl-dev
  
- name: Set package details
  set_fact:
    kerberos_pkg_ver: 2.6.2
    kerberos_pkg_name: kerberosio

- name: Set pack detaile
  set_fact:
    kerberos_pkg: "rpi3-machinery-{{ kerberos_pkg_name }}-armhf-{{ kerberos_pkg_ver }}"

- name: Set fact
  set_fact:
    kerberos_pkg_url: "https://github.com/kerberos-io/machinery/releases/download/v{{ kerberos_pkg_ver }}/{{ kerberos_pkg }}.deb"

- name: "Check if kerberos_pkg is installed"
  command: dpkg-query -W my_package
  register: my_package_check_deb
  failed_when: my_package_check_deb.rc > 1
  changed_when: my_package_check_deb.rc == 1
  when: 0

- name: "Download {{ kerberos_pkg }}"
  get_url: 
    dest: "/tmp/{{ kerberos_pkg }}.deb"
    url: "{{ kerberos_pkg_url }}"
  # when: vagrant_check_deb.rc == 1

- name: "Install {{ kerberos_pkg }}"
  become: true
  apt:
    deb: "/tmp/{{ kerberos_pkg }}.deb"
  # when: vagrant_check_deb.rc == 1

# Set machinery to start on boot
- name: ENable start at boot and start service
  become: true
  systemd:
    name: kerberosio
    state: started
    enabled: yes

# Update the packages and kernel
- name: Add repository into source list
  become: true
  apt_repository:
    repo: deb http://mirrordirector.raspbian.org/raspbian/ stretch main contrib non-free rpi
    state: present

#  sudo apt-get install -t stretch nginx php7.0 php7.0-curl php7.0-gd php7.0-fpm php7.0-cli php7.0-opcache php7.0-mbstring php7.0-xml php7.0-zip php7.0-mcrypt
- name: Install nginx
  become: true
  package:
    name: "{{ item }}"
    state: latest
  loop:
    - nginx
    - php7.0
    - php7.0-curl
    - php7.0-gd
    - php7.0-fpm
    - php7.0-cli
    - php7.0-opcache
    - php7.0-mbstring
    - php7.0-xml
    - php7.0-zip
    - php7.0-mcrypt

- name: COnfigure nginx
  become: true
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  
- name: Copy config
  become: true
  copy:
    dest: /etc/nginx/sites-enabled/kerberosio.conf
    src: kerberosio.conf

# sudo service nginx restart
- name: Restart nginx service
  become: true
  systemd:
    name: nginx
    state: restarted
