---

- name: Install packages
  apt:
    name: "{{ packages }}"
    state: latest
  when: 0

# https://hub.docker.com/_/eclipse-mosquitto
# docker run -it -p 1883:1883 -p 9001:9001 -v mosquitto.conf:/mosquitto/config/mosquitto.conf eclipse-mosquitto
- name: "Run image {{ broker.container.image }} as container {{ broker.container.name }}"
  docker_container:
    name: "{{ broker.container.name }}"
    image: "{{ broker.container.image }}"
    published_ports:
      - "{{ broker.container.ports.http }}:1883"
      - "{{ broker.container.ports.https }}:9001"
    recreate: yes
    state: started
