---

- name: Get source
  git:
    repo: "{{ registrator.project.src }}"
    dest: "/tmp/registrator"
    update: yes
  register: registrator_source

- name: Build image
  docker_image:
    path: /tmp/registrator
    name: "{{ registrator.image.name }}"
    tag: "{{ registrator.image.tag}}"
  when: registrator_source.changed

# docker run -d --name=registrator --net=host --volume=/var/run/docker.sock:/tmp/docker.sock gliderlabs/registrator:latest consul://localhost:8500
- name: "Run image {{ registrator.image.name }}:{{ registrator.image.tag}} as container {{ registrator.container.name }}"
  docker_container:
    name: "{{ registrator.container.name }}"
    image: "{{ registrator.image.name }}:{{ registrator.image.tag}}"
    command:
      - -ip="{{ ansible_host }}"
      - -resync="{{ registrator.resync }}"
      - -retry-attempts="{{ registrator.retry.attempts }}"
      - -retry-interval="{{ registrator.retry.interval }}"
      - consul://"{{ ansible_host }}":8500
    dns_servers:
      - "{{ consul_server }}"
    dns_search_domains:
      - service.consul
    hostname: "{{ registrator.container.name }}"
    network_mode: host
    recreate: yes
    restart_policy: "{{ registrator.container.restart.policy }}"
    state: started
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
  register: registartor_container_launched
