---

- name: "Create directory for configuration at {{ traefik.storage }}"
  file:
    path: "{{ traefik.storage }}"
    state: directory

- name: Copy configuration files
  copy:
    dest: "{{ traefik.storage }}/{{ item }}"
    src: "{{ item }}"
    backup: yes
  loop:
    - traefik.toml
