---

# source: https://hub.docker.com/_/traefik
# docker run -d -p 8080:8080 -p 80:80 \
# -v $PWD/traefik.toml:/etc/traefik/traefik.toml \
# -v /var/run/docker.sock:/var/run/docker.sock \
# traefik
- name: "Run image {{ traefik.image.name }}:{{ traefik.image.tag }} as service {{ traefik.service.name }}"
  docker_container:
    name: "{{ traefik.service.name }}"
    image: "{{ traefik.image.name }}:{{ traefik.image.tag}}"
    # command: "--consul --consul.endpoint={{ ansible_default_ipv4.address }}:8500"
    command:
      - --api=true
      - --debug
    # domainname: "{{ domain_name }}"
    dns_servers:
      - "{{ consul_server }}"
    dns_search_domains:
      - service.consul
    hostname: "{{ traefik.service.name }}"
    labels:
      traefik.enable: "true"
      traefik.backend: "traefik"
#      traefik.frontend.rule: "Host:traefik.{{ domain_name }}"
      # traefik.frontend.rule: "Host:${DOMAINNAME}; PathPrefixStrip: /traefik"
      traefik.frontend.rule: "PathPrefixStrip: /traefik"
      traefik.port: "8080"
      # traefik.docker.network: "{{ hcnp_network }}"
      # traefik.frontend.headers.SSLRedirect: "true"
      # traefik.frontend.headers.STSSeconds: "315360000"
      # traefik.frontend.headers.browserXSSFilter: "true"
      # traefik.frontend.headers.contentTypeNosniff: "true"
      # traefik.frontend.headers.forceSTSHeader: "true"
      # traefik.frontend.headers.SSLHost: "example.com"
      # traefik.frontend.headers.STSIncludeSubdomains: "true"
      # traefik.frontend.headers.STSPreload: "true"
      # traefik.frontend.headers.frameDeny: "true"
      # traefik.frontend.auth.basic.users: "${HTTP_USERNAME}:${HTTP_PASSWORD}"
    # network_mode: host
    # networks:
    #   - name: "{{ hcnp_network }}"
    published_ports:
      - "{{ traefik.service.ports.http }}:80"
      - "{{ traefik.service.ports.https }}:443"
      - "{{ traefik.service.ports.ui }}:8080"
    pull: yes
    recreate: yes
    restart_policy: "{{ traefik.service.restart.policy }}"
    state: started
    volumes:
      - "{{ traefik.storage }}/traefik.toml:/etc/traefik/traefik.toml"
      # - "{{ traefik.storage }}/acme.json:/etc/traefik/acme.json"
      - "{{ traefik.storage }}/html:/var/www/html"
      - "/var/run/docker.sock:/var/run/docker.sock"

- name: "register {{ traefik.service.name }} service with the local consul agent"
  consul:
    service_name: "{{ traefik.service.name }}-{{ item.value }}"
    service_port: "{{ item.value }}"
  with_dict: "{{ traefik.service.ports }}"
  when: service_consul_running
