---

# docker run -d -p 8080:8080 -p 80:80 \
# -v $PWD/traefik.toml:/etc/traefik/traefik.toml \
# -v /var/run/docker.sock:/var/run/docker.sock \
# traefik
- name: "Run image {{ traefik.image.name }}:{{ traefik.image.tag }} as container {{ traefik.container.name }}"
  docker_container:
    name: "{{ traefik.container.name }}"
    image: "{{ traefik.image.name }}:{{ traefik.image.tag}}"
    published_ports:
      - "{{ traefik.container.ports.http }}:80"
      - 8080:8080
    dns_servers:
      - "{{ consul_server }}"
    dns_search_domains:
      - service.consul
    hostname: "{{ traefik.container.name }}"
    network_mode: host
    recreate: yes
    restart_policy: "{{ traefik.container.restart.policy }}"
    state: started
    volumes:
      - "{{ traefik.storage }}/traefik.toml:/etc/traefik/traefik.toml"
      - "/var/run/docker.sock:/var/run/docker.sock"
