---

- name: "Check if {{ git }} is installed"
  command: "{{ git }} --version"
  ignore_errors: true
  changed_when: false # read-only task
  check_mode: no
  register: git_install_check

- name: Install {{ git }}
  package:
    name: "{{ packages }}"
    state: latest
  tags:
    - installation
    - git
  when: git_install_check.rc != 0

- name: Configure git
  import_tasks: configure.yml
