---

- name: configure docker
  import_tasks: configure.yml
  tags:
    - configuration
    - docker

- name: install python modules
  import_tasks: install-python-modules.yml
  tags:
    - configuration
    - docker

- name: force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers

- name: test docker
  import_tasks: test.yml
  tags:
    - test
    - docker
  when: 0
