---

gogs:
  container:
    name: gogs
    ports:
      http: 10080
      https: 10022
  image: 
    name:
      linux: "gogs/gogs"
      rpi: "gogs/gogs-rpi"
    tag: latest
  storage: "{{ storage_base }}/gogs"
  