---

consul:
  image:
    name: consul
    tag: latest
  bind: "{{ ansible_default_ipv4.address }}"
  container:
    name: consul
    ports:
      dns: 8600
      http: 8500
    restart:
      policy: always
  datacenter: hcnp
  dns_recursor: 8.8.8.8
  interfaces:
    bind: "{{ ansible_default_ipv4.interface }}"
    client: "{{ ansible_default_ipv4.interface }}"
  # network_mode: host  # must always be hsot for a container so do not change
  project:
    docker_hub: https://hub.docker.com/_/consul
    src: https://github.com/hashicorp/consul
    url: https://www.consul.io/
  resync: 120
  retry:
    attempts: -1
    interval: 12000
  volumes:
    configuration: consul_config
    data: consul_data
