---
# file: roles/pip/tasks/install.yml

- name: Check if "{{ pip }}" is installed
  command: "{{ pip }} --version"
  ignore_errors: true
  changed_when: false # read-only task
  check_mode: no
  register: pip_install_check

- name: download get-pip.py
  get_url:
    url: "{{ pip_source_url }}"
    dest: "{{ pip_download_dest }}"
  when: pip_install_check.rc != 0

- name: "install {{ pip }}"
  command: "{{ python }} --user {{ pip_download_dest }}/get-pip.py"
  when: pip_install_check.rc != 0

- name: delete get-pip.py
  file:
    path: "{{ pip_download_dest }}/get-pip.py"
    state: absent
  when: pip_install_check.rc != 0

- name: "upgrade {{ pip }} if installed"
  pip:
    name: "{{ pip }}"
    extra_args: --user
    state: latest
  when: pip_install_check.rc == 0