---
# file: roles/pip/tasks/main.yml

- name: Check if "{{ pip }}" is installed
  command: "{{ pip }} --version"
  ignore_errors: true
  changed_when: false # read-only task
  check_mode: no
  register: pip_install_check

- name: Install pip
  import_tasks: install.yml
  tags:
    - installation
    - pip
  when: pip_install_check.rc != 0

- name: "upgrade {{ pip }} if installed"
  pip:
    name: "{{ pip }}"
    extra_args: --user
    state: latest
  tags:
    - upgrade
    - pip
  when: pip_install_check.rc == 0
