---

- name: Install or upgrade pip
  include_tasks:
    file: install.yml
  loop:
    - { python: 'python2', pip: 'pip2' }
    - { python: 'python3', pip: 'pip3' }

- name: delete get-pip.py
  file:
    path: "{{ pip_download_dest }}/get-pip.py"
    state: absent
