---

git_config: [
  { key: 'http.sslVerify', value: 'true', scope: 'global' },
]

packages: []

python_modules: []

resolv_nameservers: []
resolv_domain: ""
resolv_search: []
resolv_sortlist: []
resolv_options: []
