---

git_config: [
  { key: 'http.sslVerify', value: 'true', scope: 'global' },
]

packages: [
  dnsutils,
#  git,
  python-pip,
  sshpass,
  unzip
]

python_modules: [
  docker,
  netaddr,
  python-consul
]

resolv_nameservers: []
resolv_domain: ""
resolv_search: []
resolv_sortlist: []
resolv_options: []
