---

# - name: Get source
#   git:
#     repo: "{{ radicale.project.src }}"
#     dest: "/tmp/radicale"
#     update: yes

- name: Build image
  docker_image:
    # path: /tmp/radicale
    path: ~/radicale
    name: "{{ radicale.container.image }}:{{ radicale.container.tag}}"
    tag: latest

- name: Create directory for radicale configuration
  file:
    path: "{{ radicale.storage }}"
    state: directory

- name: Copy configuration files
  copy:
    dest: "{{ radicale.storage }}/{{ item }}"
    src: "{{ item }}"
    backup: yes # not required. Create a backup file including the timestamp information so you can get the original file back if you somehow clobbered it incorrectly.
  loop:
    - config
    - logging

- name: Create directory for radicale logging
  become: true
  file:
    path: "{{ radicale.storage }}/{{ item }}"
    state: directory
  loop:
    - data
    - logs

# docker run --name=gogs -p 10022:22 -p 10080:3000 -v /var/gogs:/data gogs/gogs-rpi
- name: "Run image {{ radicale.container.image }}:{{ radicale.container.tag}} as container {{ radicale.container.name }}"
  docker_container:
    name: "{{ radicale.container.name }}"
    image: "{{ radicale.container.image }}:{{ radicale.container.tag}}"
    # command:
    #   - radicale
      # - --hosts
      # - 0.0.0.0:5232
    published_ports:
      - 5232:5232
    recreate: yes
    state: started
    volumes:
      - "{{ radicale.storage }}/config:/etc/radicale"
      - "{{ radicale.storage }}/data:/var/lib/radicale"
      - "{{ radicale.storage }}/logs:/var/log/radicale"
