---

- name: "Remove container {{ consul.container.name }}-{{ ansible_hostname }} and associated volumes"
  docker_container:
    name: "{{ consul.container.name }}-{{ ansible_hostname }}"
    keep_volumes: no
    state: absent

- name: Consul configuration volume
  docker_volume:
    name: "{{ consul.volumes.configuration }}"
    force: yes

- name: Consul data volume
  docker_volume:
    name: "{{ consul.volumes.data }}"
    force: yes

# see https://hub.docker.com/_/consul Running Consul Agent in Server Mode
# docker run -d --net=host consul agent -server -bind= -retry-join= -bootstrap-expect=
# This runs a Consul client agent sharing the host's network and advertising the external IP address to the rest of the cluster.
# Note that the agent defaults to binding its client interfaces to 127.0.0.1, which is the host's loopback interface.
# This would be a good configuration to use if other containers on the host also use --net=host,
# and it also exposes the agent to processes running directly on the host outside a container, such as HashiCorp's Nomad.
- name: "Run {{ consul.image.name }}:{{ consul.image.tag }} as container {{ consul.container.name }}-{{ ansible_hostname }} as server"
  docker_container:
    name: "{{ consul.container.name }}-{{ ansible_hostname }}"
    image: "{{ consul.image.name }}:{{ consul.image.tag }}"
    command:
      - agent
      # - -advertise="{{ ansible_default_ipv4.address }}"
      # - -bind=127.0.0.1
      - -bind={{ ansible_default_ipv4.address }}
      - -bootstrap-expect=1
      # - -client=0.0.0.0
      - -datacenter="{{ consul.datacenter }}"
      # - -dns-port="{{ consul.container.ports.dns }}"
      # - -recursor="{{ consul.dns_recursor }}"
      # - - -retry-join=
      - -server
      - -ui
      # # # - -recursor="{{ consul.dns_recursor }}"
      - -config-dir=/consul/config
      - -data-dir=/consul/data
    detach: true
    env:
      CONSUL_BIND_INTERFACE: "{{ consul.interfaces.bind }}"
      CONSUL_CLIENT_INTERFACE: "{{ consul.interfaces.client }}"
    hostname: "consul-{{ ansible_hostname }}"
    network_mode: host
    published_ports:
     - 8300:8300
     - 8301:8301
     - 8301:8301/udp
     - 8302:8302
     - 8302:8302/udp
     - 8400:8400
     - 8500:8500
     - 8600:8600
     - "{{ ansible_default_ipv4.address }}:{{consul.container.ports.dns}}:8600/udp"
    pull: yes
    recreate: yes
    restart_policy: "{{ consul.container.restart.policy }}"
    state: started
    volumes:
      - "{{ consul.volumes.configuration }}:/consul/config"
      - "{{ consul.volumes.data }}:/consul/data"
  register: consul_container_launched
  when: consul_mode == "server"

# see https://hub.docker.com/_/consul Running Consul Agent in Client Mode
# docker run -d --net=host consul agent -bind= -retry-join= 
# This runs a Consul client agent sharing the host's network and advertising the external IP address to the rest of the cluster.
# Note that the agent defaults to binding its client interfaces to 127.0.0.1, which is the host's loopback interface.
# This would be a good configuration to use if other containers on the host also use --net=host,
# and it also exposes the agent to processes running directly on the host outside a container, such as HashiCorp's Nomad.
- name: "Run {{ consul.image.name }}:{{ consul.image.tag }} as container {{ consul.container.name }}-{{ ansible_hostname }} in client mode"
  docker_container:
    name: "{{ consul.container.name }}-{{ ansible_hostname }}"
    image: "{{ consul.image.name }}:{{ consul.image.tag }}"
    command:
      - agent
      - -bind="{{ consul.bind }}"
      # - -client=0.0.0.0
      - -datacenter="{{ consul.datacenter }}"
      # - -dns-port="{{ consul.container.ports.dns }}"
      # - -recursor="{{ consul.dns_recursor }}"
      - -retry-join="{{ controller_name }}"
      - -config-dir=/consul/config
      - -data-dir=/consul/data
    detach: true
    # env:
    #   CONSUL_BIND_INTERFACE: "{{ consul.interfaces.client }}"
    #   CONSUL_CLIENT_INTERFACE: "{{ consul.interfaces.client }}"
    hostname: "consul-{{ ansible_hostname }}"
    network_mode: host
    published_ports:
     - 8300:8300
     - 8301:8301
     - 8301:8301/udp
     - 8302:8302
     - 8302:8302/udp
     - 8400:8400
     - 8500:8500
     - 8600:8600
     - "{{ ansible_host }}:{{consul.container.ports.dns}}:8600/udp"
    pull: yes
    recreate: yes
    restart_policy: "{{ consul.container.restart.policy }}"
    state: started
    volumes:
      - "{{ consul.volumes.config }}:/consul/config"
      - "{{ consul.volumes.data }}:/consul/data"
  register: consul_container_launched
  when: (consul_mode is not defined or consul_mode != "server")

- name: Wait for consul to launch
  wait_for:
    port: "{{ consul.container.ports.http }}"
    delay: 5
  when: consul_container_launched

- name: "Register {{ ansible_host }} with Consul DNS"
  uri:
    url: "http://{{ consul_server }}:{{ consul.container.ports.http }}/v1/catalog/register"
    method: PUT
    body: '{"Datacenter": "{{ consul.datacenter }}", "Node": "hcnp-hosts", "Address": "{{ ansible_default_ipv4.interface }}", "Service": {"ID": "{{ ansible_host }}", "Service": "{{ ansible_host }}", "Address": "{{ ansible_default_ipv4.interface }}", "Port": 80}}'
    body_format: json
    headers:
      Content-Type: "application/json"
    status_code: 200, 201, 204
  when: consul_container_launched
