---

# Based on https://medium.com/@mitesh_shamra/setup-hashicorp-vault-using-ansible-fa8073a70a56

# Create group and user for vault
- name: "Creating vault user group {{ vault_group }}"
  become: yes
  group: 
    name: "{{ vault_group }}"

- name: Creating vault user
  become: yes
  user:
    name: "{{ vault_user }}"
    group: "{{ vault_group }}"
    system: yes
    shell: "/sbin/nologin"
    comment: "vault nologin User"
    createhome: "no"
    state: present

# Install binary from archive
- name: Install prerequisites
  become: yes
  package:
    name: "{{ item }}"
    update_cache: yes
  with_items: "{{ vault_install_prerequisites }}"

- name: Download binary
  become: yes
  get_url:
    url: https://releases.hashicorp.com/vault/{{vault_version}}/vault_{{vault_version}}_linux_amd64.zip
    dest: /tmp/vault_{{vault_version}}_linux_amd64.zip
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: 0755
    checksum: "{{vault_checksum}}"
  register: vault_download

- name: "Unzip vault archive"
  become: yes
  unarchive:
    src: "{{ vault_download.dest }}"
    dest: /usr/local/bin
    copy: no
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: 0755

# Need to set binary capabilities on Linux, to give the Vault executable the ability to use the mlock syscall without running the process as root.
- name: "Set vault binary capabilities"
  become: yes
  capabilities:
    path: /usr/local/bin/vault
    capability: cap_ipc_lock+ep
    state: present

# Configure systemd
- name: Copy systemd init file
  become: yes
  template:
    src: init.service.j2
    dest: /etc/systemd/system/vault.service
    owner: root
    group: root
  notify: systemd_reload

- name: Create directory for configuration file
  become: yes
  file:
    path: "{{ vault_config_path }}"
    state: directory
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"

- name: config file
  become: yes
  template:
    src: vault.hcl.j2
    dest: "{{ vault_config_path }}/vault.hcl"
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: 0640
    
- name: vault service
  become: yes
  service:
    name: vault
    state: started
    enabled: yes
    