---

- name: Create Docker configuration directories
  become: yes
  file:
    path: "{{ item }}"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "0755"
  loop:
    - "/etc/docker"
    - "/etc/systemd/system/docker.service.d"
  tags:
    - configuration
    - docker

- name: Configure Docker daemon options (json)
  become: yes
  copy:
    src: "daemon.json"
    dest: "/etc/docker/daemon.json"
    owner: root
    group: root
    backup: yes
    mode: 0644
  register: docker_daemon_options 
  notify: 'restart docker'
  tags:
    - configuration
    - docker

- name: Configure Docker service
  become: yes
  copy:
    src: "docker.conf"
    dest: "/etc/systemd/system/docker.service.d/docker.conf"
    owner: root
    group: root
    backup: yes
    mode: 0644
  register: docker_service 
  notify: 'restart docker'
  tags:
    - configuration
    - docker

- name: Reload systemd daemon
  systemd:
    daemon_reload: true
  when: (docker_daemon_options is changed or docker_service is changed)
  notify: 'restart docker'
  tags:
    - configuration
    - docker

- name: Ensure Docker is started and enabled at boot
  become: yes
  service:
    name: docker
    state: "{{ docker_service_state }}"
    enabled: "{{ docker_service_enabled }}"
  tags:
    - configuration
    - docker

- name: Ensure group "docker" exists
  become: yes
  group:
    name: docker
    state: present
  tags:
    - configuration
    - docker

- name: Ensure current user is in docker group
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes
  tags:
    - configuration
    - docker
