---

# curl -fsSL get.docker.com -o get-docker.sh && sh get-docker.sh

- name: Get install script
  get_url:
    url: "{{ docker_source_url }}"
    dest: "{{ docker_download_dest }}"

- name: Run install script
  become: true
  command: "/bin/sh {{ docker_download_dest }}"
