---

# curl -fsSL get.docker.com -o get-docker.sh && sh get-docker.sh

- name: Get install script
  get_url:
    url: "{{ docker_source_url }}"
    dest: "{{ docker_download_dest }}"
  tags:
    - installation
    - docker

- name: Run install script
  become: yes
  command: "/bin/sh {{ docker_download_dest }}"
  tags:
    - installation
    - docker

- name: clean up
  file:
    path: "{{ docker_download_dest }}"
    state: absent
