---

# curl -fsSL get.docker.com -o get-docker.sh && sh get-docker.sh

- name: Get install script
  get_url:
    url: "{{ docker_source_url }}"
    dest: "{{ docker_download_dest }}"

- name: Run install script
  become: true
  command: "/bin/sh {{ docker_download_dest }}"
#  shell: "{{ docker_download_dest }}"
#    >> /tmp/get-docker.log"
  notify: restart docker

- name: Ensure Docker is started and enabled at boot.
  become: true
  service:
    name: docker
    state: "{{ docker_service_state }}"
    enabled: "{{ docker_service_enabled }}"

- name: Ensure group "docker" exists
  group:
    name: docker
    state: present

- name: "Install pip modules {{ docker_python_module.modules }}"
  pip:
    extra_args: --user
    name: "{{ docker_python_module.modules }}"
    state: latest
