---

- name: "Ensure pip modules {{ docker_python_module.modules }} are installed"
  become: yes
  pip:
    name: "{{ docker_python_module.modules }}"
    state: latest
  tags:
    - installation
    - docker
