---

# curl -fsSL get.docker.com -o get-docker.sh && sh get-docker.sh

- name: Get install script
  get_url:
    url: get.docker.com
    dest: /tmp/get-docker.sh

- name: Run install script
  become: true
  shell: /tmp/get-docker.sh >> /tmp/get-docker.log
  notify: restart docker

- name: Ensure Docker is started and enabled at boot.
  become: true
  service:
    name: docker
    state: "{{ docker_service_state }}"
    enabled: "{{ docker_service_enabled }}"

- name: Ensure group "docker" exists
  group:
    name: docker
    state: present

- name: "Install pip modules {{ docker_python_module.modules }}"
  become: true
  pip:
    extra_args: --user
    name: "{{ docker_python_module.modules }}"
    state: latest
