---

- name: "Check if {{ docker }} is installed"
  command: "{{ docker }} --version"
  ignore_errors: true
  changed_when: false # read-only task
  check_mode: no
  register: docker_install_check
  tags:
    - installation
    - docker

- name: install docker
  import_tasks: install.yml
  tags:
    - installation
    - docker
  when: docker_install_check.rc != 0 or docker_upgrade

- name: configure docker
  import_tasks: configure.yml
  tags:
    - configuration
    - docker

- name: force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers

- name: test docker
  import_tasks: test.yml
  tags:
    - test
    - docker
  when: 0