---

- name: "Check if {{ docker }} is installed"
  command: "{{ docker }} --version"
  ignore_errors: true
  changed_when: false # read-only task
  check_mode: no
  register: docker_install_check
  tags:
    - installation
    - docker

- name: install docker
  import_tasks: install.yml
  tags:
    - installation
    - docker
  when: docker_install_check.rc != 0 or docker_upgrade

- name: Create Docker configuration directories
  become: true
  file:
    path: "{{ item }}"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "0755"
  loop:
    - "/etc/docker"
    - "/etc/systemd/system/docker.service.d"
  tags:
    - configuration
    - docker

- name: Configure Docker daemon options (json)
  become: true
  copy:
    src: "daemon.json"
    dest: "/etc/docker/daemon.json"
    owner: root
    group: root
    backup: yes
    mode: 0644
  register: docker_daemon_options 
  notify: 'restart docker'
  tags:
    - configuration
    - docker

- name: Configure Docker service
  become: true
  copy:
    src: "docker.conf"
    dest: "/etc/systemd/system/docker.service.d/docker.conf"
    owner: root
    group: root
    backup: yes
    mode: 0644
  register: docker_service 
  notify: 'restart docker'
  tags:
    - configuration
    - docker

- name: Reload systemd daemon
  systemd:
    daemon_reload: true
  when: (docker_daemon_options is changed or docker_service is changed)
  notify: 'restart docker'
  tags:
    - configuration
    - docker

- name: Ensure Docker is started and enabled at boot
  become: true
  service:
    name: docker
    state: "{{ docker_service_state }}"
    enabled: "{{ docker_service_enabled }}"
  tags:
    - configuration
    - docker

- name: Ensure group "docker" exists
  become: true
  group:
    name: docker
    state: present
  tags:
    - configuration
    - docker

- name: Ensure current user is in docker group
  become: true
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes
  tags:
    - configuration
    - docker

- name: "Ensure pip modules {{ docker_python_module.modules }} are installed"
  become: true
  pip:
    # executable: pip3
    # extra_args: --user
    name: "{{ docker_python_module.modules }}"
    state: latest
  tags:
    - configuration
    - docker

- name: force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers

- name: test docker
  import_tasks: test.yml
  tags:
    - test
    - docker
