---


# https://www.portainer.io/installation/
# docker run -d -p 9000:9000 -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer
- name: Run Portainer
    docker_container:
      name: portainer
      image: portainer/portainer:arm
      published_ports:
        - 9000:9000
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - portainer_data:/data
