---

- hosts: all

  remote_user: pi
  
  tasks:
    - name: test connection
      ping:

    - hosts: all
  tasks:
    - debug:
        msg: task1

    - import_tasks: stuff.yml
      when: hostvar is defined