---

# Run up Cadvisor
- hosts: rpi-home-network-nodes

  tasks:

    - import_role:
        name: cadvisor
        tasks_from: nomad.yml
      environment:
        NOMAD_ADDR: "http://{{ ansible_default_ipv4.address }}:4646"
      tags:
        - cadvisor
        - services
