---

- hosts: consul_instances

  become: true
  
  tasks:

    - import_role:
        name: upgrade
      tags:
        - upgrade

    - import_role:
        name: brianshumate.consul
      tags:
        - consul
