---

- hosts: consul_instances

  become: yes
  
  vars:
    consul_dnsmasq_enable: yes

  tasks:

    - import_role:
        name: brianshumate.consul
      tags:
        - consul

    - debug:
        var: consul_servers
