---

- hosts: "{{ host }}"

  remote_user: "{{ user }}"

 # become: yes

 # become_user: "{{ user }}"

  tasks:
  - name: make directory
    file:
      path: "/home/{{ user }}/.ssh"
      state: directory

  - name: create empty file
    file:
      path: "/home/{{ user }}/.ssh/authorized_keys"
      state: touch

  - name: put pubkey
    lineinfile:
      path: "/home/{{ user }}/.ssh/authorized_keys"
      line: "{{ pubkey }}"
