---

- hosts: development-system

  roles:
    - common
    - git-client
    - docker
    - consul-container
    # - registrator
    - portainer
    # - frontail
    # - cadvisor
    # - openhab
    - traefik
 