---

# Run up core services
- hosts: hcnp_nodes

  vars:

    run_portainer: yes

  pre_tasks:

    - name: Create hcnp_node_list
      set_fact:
        hcnp_node_list: "{{ groups['hcnp_nodes'] | map('extract', hostvars, 'ansible_host') | list }}"
      when: groups['hcnp_nodes'] is defined

    - name: "Run Portainer Nomad job"
      import_role:
        name: portainer
        tasks_from: configuration.yml
      tags:
        - portainer
      when: run_portainer

  tasks:

    - name: "Run Portainer Nomad job"
      import_role:
        name: portainer
        tasks_from: nomad.yml
      tags:
        - portainer
      when: nomad_node_role == 'server' and run_portainer
