---

all:

  hosts:

    mqttbroker-node:
      ansible_host: 192.168.1.50
      ansible_user: pi
      consul_server: 192.168.1.114
    nextcloud-node:
      ansible_host: 192.168.1.51
      ansible_user: pi
      consul_server: 192.168.1.114
    emonpi-node:
      ansible_host: 192.168.1.52
      ansible_user: pi
      consul_server: 192.168.1.114
    openhab-node:
      ansible_host: 192.168.1.53
      ansible_user: openhabianpi
      consul_server: 192.168.1.114
    home-assistant-node:
      ansible_host: 192.168.1.54
      ansible_user: pi
      consul_server: 192.168.1.114
    gogs-node:
      ansible_host: 192.168.1.55
      ansible_user: pi
      consul_server: 192.168.1.114
    sandpit:
      ansible_host: 192.168.1.10
      ansible_user: pi
      consul_server: 192.168.1.114
    development-system:
      ansible_host: localhost
      ansible_connection: local
      ansible_user: philip
      consul_mode: server
      consul_server: 192.168.1.114

  children:
  
    rpi-home-network-nodes:
      hosts:
        mqttbroker-node:
        nextcloud-node:
        emonpi-node:
        openhab-node:
        home-assistant-node:
        gogs-node:
        sandpit:
        development-system:

    mqttbroker-nodes:
      hosts:
        mqttbroker-node:

    nextcloud-nodes:
      hosts:
        nextcloud-node:

    emonpi-nodes:
      hosts:
        emonpi-node:

    openhab-nodes:
      hosts:
        openhab-node:

    home-assistant-nodes:
      hosts:
        home-assistant-node:

    gogs-nodes:
      hosts:
        gogs-node:

    sandpit-nodes:
      hosts:
        sandpit:
