---

# Install and configure nomad
- hosts: nomad_instances

  become: true

  vars:
    nomad_use_consul: true
    nomad_bootstrap_expect: 1
    nomad_docker_enable: true

  tasks:

    - import_role:
        name: brianshumate.nomad
      tags:
        nomad

    - debug:
        var: nomad_servers
