---

# Install and configure nomad
- hosts: nomad_instances

  vars:
    nomad_use_consul: yes
    nomad_bootstrap_expect: 1
    nomad_docker_enable: yes

  tasks:

    - name: "Run nomad role"
      import_role:
        name: nomad
      tags:
        nomad
