---

- hosts: openhab-nodes

  remote_user: pi

  tasks:
  
    - import_role:
        name: traefik
      tags:
        - services
        - common

    - import_role:
        name: radicale
      tags:
        - services
        - radicale

    - import_role:
        name: openhab
      tags:
        - services
        - openhab
