---

- hosts: openhab-nodes

  tasks:

    - import_role:
        name: common
      tags:
        - upgrade
  
    - import_role:
        name: docker
      tags:
        - docker
        
    - import_role:
        name: traefik
      tags:
        - services
        - common

    - import_role:
        name: radicale
      tags:
        - services
        - radicale

    - import_role:
        name: openhab
      tags:
        - services
        - openhab
