---

- hosts: openhab-nodes

  tasks:

    - import_role:
        name: common
      tags:
        - upgrade
  
    - import_role:
        name: docker
      tags:
        - docker
        
    - import_role:
        name: traefik
      tags:
        - common
        - services

    - import_role:
        name: radicale
      tags:
        - radicale
        - services

    - import_role:
        name: openhab
      tags:
        - openhab
        - services
