---

- hosts: rpi-home-network-nodes

  tasks:

    - set_fact:
        consul_iface: "\
          {% if ansible_os_family == 'Windows' %}\
            {{ lookup('env','CONSUL_IFACE') | default(ansible_interfaces[0].interface_name, true) }}\
          {% else %}\
            {{ lookup('env','CONSUL_IFACE') | default(ansible_default_ipv4.interface, true) }}\
          {% endif %}"
    
    - set_fact:
        consul_bind_address: "\
          {% if ansible_system == 'FreeBSD' %}\
            {{ lookup('env','CONSUL_BIND_ADDRESS') | default(hostvars[inventory_hostname]['ansible_'+ consul_iface ]['ipv4'][0]['address'], true) }}\
          {% elif ansible_os_family == 'Windows'  %}\
            {{ lookup('env','CONSUL_BIND_ADDRESS') | default(hostvars[inventory_hostname]['ansible_ip_addresses'][0], true) }}\
          {% else %}\
            {{ lookup('env','CONSUL_BIND_ADDRESS') | default(hostvars[inventory_hostname]['ansible_'+ consul_iface ]['ipv4']['address'], true) }}\
          {% endif %}"

    - debug:
        var: consul_iface

    - debug:
        var: consul_bind_address

    - import_role:
        name: traefik
        tasks_from: configure.yml

    - import_role:
        name: traefik
        tasks_from: nomad.yml
      environment:
        NOMAD_ADDR: "http://{{ consul_bind_address }}:4646"
      tags:
        - traefik
        - services
