---

# Install and configure vault
- hosts: vault_instances

  tasks:

    - import_role:
        name: vault
      tags:
        - vault

    - import_role:
        name: vault-init
      tags:
        - vault
      when: 0

    - import_role:
        name: vault-unseal
      tags:
        - vault
