---

# Create group
- name: "Create system group {{ openhab.group.name }} with id {{ openhab.group.id }}"
  become: yes
  group:
    name: "{{ openhab.group.name }}"
    state: present
    gid: "{{openhab.group.id }}"
    system: yes

# sudo useradd -r -s /sbin/nologin openhab
- name: Create system user {{ openhab.user.name }} with id {{ openhab.user.id }}"
  become: yes
  user:
    name: "{{ openhab.user.name }}"
    create_home: no
    group: "{{ openhab.group.name }}"
    system: yes
    shell: /sbin/nologin
    uid: "{{ openhab.user.id }}"

# usermod -a -G openhab <user>
- name: "Add user {{ ansible_user }} to group {{ openhab.group.name }}"
  become: yes
  user:
    name: "{{ ansible_user }}"
    groups: "{{ openhab.group.name }}"
    append: yes

# Create directories
- name: "Create base directory {{ openhab.directories.base }}"
  become: yes
  file:
    name: "{{ openhab.directories.base }}"
    state: directory
    owner: "{{ openhab.user.name }}"
    group: "{{ openhab.group.name }}"
    mode: 0755

# Create data directories
- name: Create data directories
  become: yes
  file:
    name: "{{ openhab.directories.base }}/{{ item }}"
    state: directory
    owner: "{{ openhab.user.name }}"
    group: "{{ openhab.group.name }}"
    mode: 0755
  loop: "{{ openhab.directories.data }}"

# Clone configuration
- name: "Clone configuration into {{ openhab.directories.base }}/conf"
  become: yes
  git:
    repo: 'https://{{ github_user | urlencode }}:{{ github_password | urlencode }}@{{ openhab.configuration.repo }}'
    # repo: 'https://github.com/greenthegarden/openhab2-configuration.git'
    dest: "{{ openhab.directories.base }}/conf"
    force: yes
    update: yes
  register: openhab_source
  when: 0
  
- name: "Set permissions on {{ openhab.directories.base }}/conf"
  become: yes
  file:
    dest: "{{ openhab.directories.base }}/conf"
    owner: "{{ openhab.user.name }}"
    group: "{{ openhab.group.name }}"
    mode: 0755
    recurse: yes

# docker run --name=gogs -p 10022:22 -p 10080:3000 -v /var/gogs:/data gogs/gogs-rpi
- name: "Run image {{ openhab.image.name }}:{{ openhab.image.tag }} as container {{ openhab.container.name }}"
  docker_container:
    name: "{{ openhab.container.name }}"
    image: "{{ openhab.image.name }}:{{ openhab.image.tag }}"
    detach: yes
    env:
      EXTRA_JAVA_OPTS: "-Duser.timezone=Australia/Adelaide"
      USER_ID: "{{ openhab.user.id }}"
      GROUP_ID: "{{ openhab.group.id }}"
    # dns_servers:
    #   - "{{ consul_server }}"
    # dns_search_domains:
    #   - service.consul
    hostname: "{{ openhab.container.name }}"
    interactive: yes
    keep_volumes: yes
    memory: 512m
    network_mode: host  # needs to be host to support UPnP discorvery
    published_ports:
      - "{{ openhab.container.ports.http }}:8080"
      - "{{ openhab.container.ports.https }}:8443"
      - "{{ openhab.container.ports.ssh }}:8101"
      - "{{ openhab.container.ports.lsp }}:5007"
    # pull: true
    recreate: yes
    restart_policy: "{{ openhab.container.restart.policy }}"
    state: started
    tty: yes
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - "{{ openhab.directories.base }}/addons:/openhab/addons"
      - "{{ openhab.directories.base }}/conf:/openhab/conf"
      - "{{ openhab.directories.base }}/userdata:/openhab/userdata"
  register: openhab_container_launched
