---

consul:
  image:
    name: consul
    tag: latest
  container:
    name: consul
    ports:
      dns: 53
      http: 8500
    restart:
      policy: always
  datacenter: hcnp
  dns_recursor: 8.8.8.8
  interfaces:
    bind: eth0
    client: eth0
  network_mode: host
  project:
    src: https://github.com/gliderlabs/registrator
    url: https://github.com/gliderlabs/registrator
  resync: 120
  retry:
    attempts: -1
    interval: 12000
  volumes:
    configuration: consul_config
    data: consul_data
