---

consul_version: "1.4.2"
consul_checksum: "sha256:ecdddbc87e7f882c3f9d94e8449865fde553e6f443234a1787414fdacef7af55"
consul_install_prerequisites: ['unzip']
consul_user: "consul"
consul_group: "consul"
consul_config_path: "/etc/consul.hcl"
